name: Build and run

on:
  push:

jobs:
  build-and-run:
    name: Build and run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup interface
        run: |
          set -x
          set -e
          default_route=$(ip route show default | awk '/default/ {print $3}')
          echo "Default route: $default_route"
          
          sudo ip tuntap add name tap0 mode tap user $USER
          sudo ip link set tap0 up
          sudo ip addr add 192.168.69.100/24 dev tap0

          sudo iptables -t nat -A POSTROUTING -s 192.168.69.0/24 -j MASQUERADE
          sudo sysctl net.ipv4.ip_forward=1
          
          # Some distros have a default policy of DROP. This allows the traffic.
          sudo iptables -A FORWARD -i tap0 -s 192.168.69.0/24 -j ACCEPT
          sudo iptables -A FORWARD -o tap0 -d 192.168.69.0/24 -j ACCEPT
          ifconfig
          ip link show tap0
          ip addr show tap0

      - name: Dependencies
        run: |
          #sudo apt-get update
          sudo apt-get install -y libpcap-dev

      - name: Cache rust build
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build
          sudo mv target/debug/ya-smoltcp /usr/bin/ya-smoltcp

      - name: Spawn file server
        run: |
          python3 -m http.server 8000 &

      - name: Start tcpdump
        run: |
          sudo tcpdump -i eth0 -w tcpdump.log &

      - name: Run
        run: |
          set -x 
          ip_address=$(hostname -I | awk '{print $1}')
          cargo run --example httpclient -- --tap tap0 5.9.155.174 http://5.9.155.174:8000/
          sudo kill $(pidof tcpdump)
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug

      - name: Upload tcpdump
        uses: actions/upload-artifact@v4
        with:
          name: tcpdump.log
          path: tcpdump.log