name: Build and run

on:
  push:

jobs:
  build-and-run:
    name: Build and run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          #sudo apt-get update
          sudo apt-get install -y libpcap-dev

      - name: Cache rust build
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build
          sudo mv target/debug/ya-smoltcp /usr/bin/ya-smoltcp
          
