name: Build and run

on:
  push:

jobs:
  build-and-run:
    name: Build and run

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build
          sudo mv target/debug/ya-smoltcp /usr/bin/ya-smoltcp
          
